<?php

namespace YT\CustomerRegisterForm\Ui\DataProvider;

use Magento\Framework\App\Request\DataPersistorInterface;
use Magento\Ui\DataProvider\Modifier\PoolInterface;
use Magento\Ui\DataProvider\ModifierPoolDataProvider;
use YT\CustomerRegisterForm\Model\ResourceModel\CustomerProfile\CollectionFactory;

class CustomerFormDataProvider extends ModifierPoolDataProvider
{
    /**
     * @var \Magento\Cms\Model\ResourceModel\Block\Collection
     */
    protected $collection;

    /**
     * @var DataPersistorInterface
     */
    protected $dataPersistor;

    /**
     * @var array
     */
    protected $loadedData;

    /**
     * Constructor
     *
     * @param string $name
     * @param string $primaryFieldName
     * @param string $requestFieldName
     * @param CollectionFactory $collectionFactory
     * @param DataPersistorInterface $dataPersistor
     * @param array $meta
     * @param array $data
     * @param PoolInterface|null $pool
     */
    public function __construct(
        $name,
        $primaryFieldName,
        $requestFieldName,
        CollectionFactory $collectionFactory,
        DataPersistorInterface $dataPersistor,
        array $meta = [],
        array $data = [],
        PoolInterface $pool = null
    ) {
        $this->collection = $collectionFactory->create();
        $this->dataPersistor = $dataPersistor;
        parent::__construct($name, $primaryFieldName, $requestFieldName, $meta, $data, $pool);
    }

    public function getFieldsMetaInfo($fieldSetName)
    {
        return parent::getFieldsMetaInfo($fieldSetName); // TODO: Change the autogenerated stub
    }

    public function getMeta()
    {
        $randomChecked = rand(0, 1);
        return [
            'random_check' => [
                'arguments' => [
                    'data' => [
                        'config' => [
                            'value' => (string) $randomChecked,
                        ]
                    ]
                ]
            ]
        ];
    }

    /**
     * Get data
     *
     * @return array
     */
    public function getData()
    {
        if ($this->loadedData) {
            return $this->loadedData;
        }

        $this->loadedData[null]['random_check_checked'] = true;

        return $this->loadedData;
    }
}
